DROP TABLE IF EXISTS CASE;
DROP TABLE IF EXISTS GRILLE;
DROP TABLE IF EXISTS JOUEUR;
DROP TABLE IF EXISTS PARTIE;

CREATE TABLE CASE (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   x INTEGER NOT NULL,
   y INTEGER NOT NULL,
   colour INTEGER NOT NULL,
   idgrille INTEGER NOT NULL
);

CREATE TABLE GRILLE(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  taille INTEGER NOT NULL
);

CREATE TABLE JOUEUR(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  nickname VARCHAR NOT NULL,
  colour INTEGER NOT NULL
);

CREATE TABLE PARTIE(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  idgrille INTEGER NOT NULL,
  idjoueur1 INTEGER NOT NULL,
  idjoueur2 INTEGER NOT NULL,
  tourjoueur INTEGER NOT NULL
);